In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset("titanic")  # In sns their is pre built data set that we can load that's why we are using

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [4]:
# 1st we need to make ready the data

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [8]:
# You can see their is too much null values in deck column , so we need to drop the columns

In [9]:
df.drop([ 'embark_town', 'class', 'alive','who', 'adult_male', 'deck'],axis = 1,inplace = True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [11]:
# now you can see in age , embarked there is some null or missing values

In [12]:
df["age"].fillna(df["age"].mean(),inplace = True)

In [13]:
# in embarked you can remove two null values's row instead of fill by mean or median or mode

In [14]:
df.dropna(subset=["embarked"],inplace = True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [17]:
# In here we predict survived or not
# so we can lebel encoding for catagorical values (whose has not int values)

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [21]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True


In [22]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df["embarked"])

In [25]:

df = df.astype(int)

In [26]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22,1,0,7,2,0
1,1,1,0,38,1,0,71,0,0
2,1,3,0,26,0,0,7,2,1
3,1,1,0,35,1,0,53,2,0
4,0,3,1,35,0,0,8,2,1


In [27]:
# Here we can do scaling for age and fare to scale in one lebel, but here we will not apply , do apply direct logistic regression , we will do it in KNN

In [28]:
# Let divide in X and Y lebel
x = df.drop("survived",axis = 1)     # as you know we will predict survived so we drop the columns form x

y = df["survived"]                     # replace in Y

In [30]:
from sklearn.model_selection import train_test_split   # just split for train and test

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [33]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [34]:
y_pred = model.predict(X_test)

In [35]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [36]:
y_test

,survived
281,0
435,1
39,1
418,0
585,1
...,...
433,0
807,0
25,1
85,1


In [37]:
# 2nd part is model evalution

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
# just import all things

In [40]:
accuracy_score(y_test,y_pred)  # here is model accuracy

0.8033707865168539

In [42]:
confusion_matrix(y_test,y_pred)   # match with note book

array([[90, 19],
       [16, 53]])

In [43]:
print(classification_report(y_test,y_pred))  # you can see all details about metrics evalution

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [ ]:
# KNN part

In [45]:
# for knn we need to do feature scalling

In [49]:
X_train    # feature scalling for age , fare, sibsp , ...

,pclass,sex,age,sibsp,parch,fare,embarked,alone
708,1,0,22,0,0,151,2,1
240,3,0,29,1,0,14,0,0
382,3,1,32,0,0,7,2,1
792,3,0,29,8,2,69,2,0
683,3,1,14,5,2,46,2,0
...,...,...,...,...,...,...,...,...
107,3,1,29,0,0,7,2,1
271,3,1,25,0,0,0,2,1
862,1,0,48,0,0,25,2,1
436,3,0,21,2,2,34,2,0


In [50]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [53]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [54]:
from sklearn.neighbors import KNeighborsClassifier  # import  KNN algo
knn_model = KNeighborsClassifier(n_neighbors=5)

In [55]:
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [56]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [58]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
# just import all things  to model evalution

In [60]:
accuracy_score(y_test,y_pred_knn)  # here is model accuracy

0.7752808988764045

In [61]:
# Now you can compare the accuracy score with logistic regression

In [62]:
confusion_matrix(y_test,y_pred_knn)   # match with note book

array([[89, 20],
       [20, 49]])

In [64]:
print(classification_report(y_test,y_pred))  # you can see all details about metrics evalution

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [65]:
# Thus we can explore all algo , and will select that is  more accurate

In [66]:
  # Naive byes

In [67]:
X_train

,pclass,sex,age,sibsp,parch,fare,embarked,alone
708,1,0,22,0,0,151,2,1
240,3,0,29,1,0,14,0,0
382,3,1,32,0,0,7,2,1
792,3,0,29,8,2,69,2,0
683,3,1,14,5,2,46,2,0
...,...,...,...,...,...,...,...,...
107,3,1,29,0,0,7,2,1
271,3,1,25,0,0,0,2,1
862,1,0,48,0,0,25,2,1
436,3,0,21,2,2,34,2,0


In [68]:
X_train_scaled

array([[-1.58410418, -1.40530972, -0.58667407, ...,  2.42752104,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.35872483,
        -1.95246446, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.50108776,
         0.58770431,  0.81076671],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.13501166,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.66286134, ...,  0.04802639,
         0.58770431, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.4807502 ,
         0.58770431,  0.81076671]])

In [69]:
# You can see their has two data we will contiue with x_train data

In [70]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train,y_train)

GaussianNB()

In [71]:
y_pred_nb = nb_model.predict(X_test)

In [72]:
y_pred_nb

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [73]:
accuracy_score(y_test,y_pred_nb)  # here is model accuracy

0.7752808988764045

In [74]:
confusion_matrix(y_test,y_pred_nb)   # match with note book

array([[84, 25],
       [15, 54]])

In [75]:
print(classification_report(y_test,y_pred_nb))  # you can see all details about metrics evalution

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [76]:
 # Decision Tree

In [79]:
from sklearn import tree
dt_model = tree.DecisionTreeClassifier()
dt_model.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [78]:
# Here you also need to scaling

In [81]:
y_pred_dt = dt_model.predict(X_test_scaled)

In [82]:
y_pred_dt

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0])

In [88]:
accuracy_score(y_test,y_pred_dt)  # here is model accuracy

0.7640449438202247

In [89]:
confusion_matrix(y_test,y_pred_dt)   # match with note book

array([[86, 23],
       [19, 50]])

In [90]:
print(classification_report(y_test,y_pred_dt))  # you can see all details about metrics evalution

              precision    recall  f1-score   support

           0       0.82      0.79      0.80       109
           1       0.68      0.72      0.70        69

    accuracy                           0.76       178
   macro avg       0.75      0.76      0.75       178
weighted avg       0.77      0.76      0.77       178



In [94]:
from sklearn.svm import SVC
svm_model = SVC(kernel = 'rbf')  # defalut there is rdf kernal ( if you do not give  manulaly)# There is many kernal , but RDF use widely
svm_model.fit(X_train_scaled,y_train)  # There is also scaled version needed

SVC()

In [97]:
y_pred_svm = svm_model.predict(X_test_scaled)

In [98]:
y_pred_svm

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [99]:
accuracy_score(y_test,y_pred_svm)  # here is model accuracy

0.8258426966292135

In [100]:
confusion_matrix(y_test,y_pred_svm)   # match with note book

array([[96, 13],
       [18, 51]])

In [101]:
print(classification_report(y_test,y_pred_dt))  # you can see all details about metrics evalution

              precision    recall  f1-score   support

           0       0.82      0.79      0.80       109
           1       0.68      0.72      0.70        69

    accuracy                           0.76       178
   macro avg       0.75      0.76      0.75       178
weighted avg       0.77      0.76      0.77       178



In [ ]:
# At last SVM has best predict accuracy so we will use that here